### ISSUE TITLE
cmake 에러

### ISSUE THREAD

**Issue by baejaeho18** [InternetOfTough/CCTV_HaLow#2]
![image](https://github.com/InternetOfTough/CCTV_HaLow/assets/37645490/c9530868-703d-414e-b543-05e01e77624f)

cmake .. 단계에서 발생한 에러입니다.
확인해보니 cmake version이 3.25.1이더라고요. cmake 업데이트 이후 다시 해보겠습니다.

**Comment by baejaeho18** [comment]
![image](https://github.com/InternetOfTough/CCTV_HaLow/assets/37645490/f7de6a18-5b98-4c2e-8e6e-14ee3e698bd3)

**Comment by jjsskk** [comment]
"could not find openssl" 에러 나오신 분은 os에 기본적으로 openssl 라이브러리가 안깔려서 그런거 같아요!
```
sudo apt-get update
sudo apt-get install libssl-dev
```
위 명령어 실행해보시고 다른 에러 나오면 이렇게 올려주시면 됩니다

**Comment by baejaeho18** [comment]
openssl 설치 이후 ./bootstrap 명령어에서 발생하던 에러는 해결되었습니다!
