### ISSUE TITLE
OpenCV 빌드 수행 시stdlib.h 관련 에러 발생 시에

### ISSUE THREAD

**Issue by YooJuno** [InternetOfTough/CCTV_HaLow#3]
어떻게 해결해야 할까요

**Comment by YooJuno** [comment]
$ sudo apt install --only-upgrade gcc

이 명령어로 gcc만 업그레이드 후에 다시 OpenCV 빌드 수행해주면 에러 해결됨

**Comment by jjsskk** [comment]
issue #2
